//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "nanoFramework_Maixduino.h"
#include "nanoFramework_Maixduino_nanoFramework_Maixduino_KPUImage.h"

using namespace nanoFramework_Maixduino::nanoFramework_Maixduino;


HRESULT Library_nanoFramework_Maixduino_nanoFramework_Maixduino_KPUImage::LoadKPUImage___STATIC__SZARRAY_U1__I4( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        signed int param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 0, param0 ) );

        CLR_RT_TypedArray_UINT8 retValue = KPUImage::LoadKPUImage( param0, hr );
        NANOCLR_CHECK_HRESULT( hr );
        SetResult_UINT8_ARRAY( stack, retValue );
    }
    NANOCLR_NOCLEANUP();
}
